### ISSUE TITLE
Unit Test Problem - addressBook.unit.js 

### ISSUE THREAD

**Issue by alberttai1** [liamks/csc490-a3#3]
Hi Professor Kaufman,

I believe there is an issue with the unit test addressBook.unit.js with the second test in remove given that the length should be 4 as Michael is removed. This also results in add unit test breaking since it should be 5 given that it was only 4. 

```
  describe('remove', function(){
    it('should return Michael from the list and return him', function(){
      expect(addrBook.remove('d4').name).toBe('Michael Moldaver');
      expect(addrBook.all().length).toBe(4);
    });

    it('should fail to locate Johny (id yy) and return null (e.g. person not found)', function(){
      expect(addrBook.remove('yy')).toBe(null);
      expect(addrBook.all().length).toBe(5);
    });
  });

  describe('add', function(){
    it('should add a person to the array of people', function(){
      var person = {id: '44', name: 'asdf', dob: 'july 1, 2004'};
      addrBook.add(person);
      expect(addrBook.all().length).toBe(6);
    });
  });
```

should be:

```
describe('remove', function(){
    it('should return Michael from the list and return him', function(){
      expect(addrBook.remove('d4').name).toBe('Michael Moldaver');
      expect(addrBook.all().length).toBe(4);
    });

    it('should fail to locate Johny (id yy) and return null (e.g. person not found)', function(){
      expect(addrBook.remove('yy')).toBe(null);
      expect(addrBook.all().length).toBe(4);
    });
  });

  describe('add', function(){
    it('should add a person to the array of people', function(){
      var person = {id: '44', name: 'asdf', dob: 'july 1, 2004'};
      addrBook.add(person);
      expect(addrBook.all().length).toBe(5);
    });
  });
```

I could be wrong given that I'm coding late at night, but I definitely know my add function is working and it is not passing the unit test. However, if I remove the "remove unit tests" it passes so I know it goes in order therefore each unit tests affect another.

**Comment by kawine** [comment]
In addition to the add and remove unit tests mentioned above, the 'should return null if it cannot find the person to update' will also fail. This is because the person {id: '44', name: 'asdf', dob: 'july 1, 2004'} was added to the AddressBook during the add test, and so that entry can indeed be updated and will not return 'null' like the test expects.

**Comment by liamks** [comment]
@kawine and @alberttai1 good find, this is a fault on my end. I've updated master with a potential fix. To fix it on your local version pull from origin, or update **line 14** in addressBook.unit.js to:

``` javascript
addrBook.people = angular.copy(people);
```

This creates a deep copy of people and ensures that every unit tests starts from scratch - state from one test shouldn't overflow to another.

**Comment by alberttai1** [comment]
Thanks for the quick fix @liamks  :), I'll close this issue then.
